AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create API gateway
Parameters:
  stackname:
    Type: String
    Description: Main Stack Name
  vpcid:
    Type: String
    Description:  VPC ID
  publicsubnetA:
    Type: String
    Description: Public Subnet A
  publicsubnetB:
    Type: String
    Description: Public Subnet B
Resources:
  networklb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: 
        Fn::Join:
          - '-'
          - - !Ref stackname
            - 'nlb'
      Scheme: 'internet-facing'
      Type: 'network'
      Subnets:
        - !Ref publicsubnetA
        - !Ref publicsubnetB
  mysfitstargetgrp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn:
      - networklb
    Properties:
      Name: 
        Fn::Join:
          - '-'
          - - !Ref stackname
            - '-targetgroup'
      Port: 8080
      Protocol: TCP
      TargetType: ip
      VpcId: !Ref vpcid
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: '/'
      HealthCheckProtocol: 'HTTP'
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
  mysfitslistener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - mysfitstargetgrp
    Properties:
      LoadBalancerArn: !Ref networklb
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref mysfitstargetgrp
Outputs:
  loadbalancerarn:
    Description: Network LoadBalancer ARN
    Value: !Ref networklb
  targetgrparn:
    Description: TargetGroup ARN
    Value: !Ref mysfitstargetgrp
  loadbalancerdns:
    Description: DNS Name for the loadbalancer
    Value: !GetAtt networklb.DNSName
    