AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to create ECS Service'
Parameters:
  mysfitsecscluster:
    Type: String
    Description: ECS Cluster Name
  mysfitstaskdefinition:
    Type: String
    Description: TaskDefinition ARN for mysfits application
  mysfitstargetgrp:
    Type: String
    Description: Mysfits TargetGroupArn
  VpcId:
    Type: String
    Description: VPC ID
  PrivateSubnetA:
    Type: String
    Description: Private Subnet A
  PrivateSubnetB:
    Type: String
    Description: Private Subnet B
Resources:
  mysfitsservicedefinition:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: 'MythicalMysfits-Service'
      Cluster: !Ref mysfitsecscluster
      LaunchType: 'FARGATE'
      DesiredCount: 1
      TaskDefinition: !Ref mysfitstaskdefinition
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 0
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: 'DISABLED'
          Subnets:
            - !Ref PrivateSubnetA
            - !Ref PrivateSubnetB
          SecurityGroups:
            - !Ref FargateContainerSecurityGroup
      LoadBalancers:
        - ContainerName: 'MythicalMysfits-Service'
          ContainerPort:  8080
          TargetGroupArn: !Ref mysfitstargetgrp
  FargateContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the fargate containers from the Internet
      VpcId: !Ref VpcId
      SecurityGroupIngress:
          # Allow access to NLB from anywhere on the internet
          - CidrIp: '10.10.0.0/16'
            IpProtocol: -1
Outputs:
  ServiceName:
    Description: ECS Service Name
    Value: !GetAtt mysfitsservicedefinition.Name