AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create Static website on S3
Parameters:
  S3BucketName:
    Type: String
    Description: Bucket Name to host static website
Resources:
  S3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Delete  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Action: 's3:GetObject'
            Effect: 'Allow'
            Principal: '*'
            Resource: 
              'Fn::Join':
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3bucket
                  - '/*'
